apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: busybox
  name: busybox-$GREEN_VERSION
  namespace: default
  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: busybox
        version: "$GREEN_VERSION"
        colour: green
    spec:
      containers:
      - args:
        - sh
        - -c
        - while true; do { echo -e 'HTTP/1.1 200 OK\r\n';      echo -e 'smallest http
          server\nversion $GREEN_VERSION\nstatus ${STATUS}'; } | nc -l -p  8080; done
        image: busybox
        imagePullPolicy: Always
        name: busybox2
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-04-30T13:29:20Z
    lastUpdateTime: 2018-04-30T13:29:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
